backend:
  name: github
  repo: info-dealsdee/DealsDee
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "reviews"
    label: "รีวิว (Reviews)"
    folder: "app/content/reviews"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - label: "หัวข้อ (Title)"
        name: "title"
        widget: "string"
        required: true
      - label: "Slug (URL)"
        name: "slug"
        widget: "string"
        required: true
      - label: "วันที่เผยแพร่ (Date)"
        name: "date"
        widget: "datetime"
        default: ""
        required: true
      - label: "ผู้เขียน (Author)"
        name: "author"
        widget: "string"
        default: "Dealsdee Team"
      - label: "หมวดหมู่ (Category)"
        name: "category"
        widget: "select"
        options:
          - "Office Chairs"
          - "Monitors" 
          - "Desks"
          - "Keyboards"
          - "Mouse"
          - "Accessories"
          - "Smart Home"
      - label: "รูปภาพหลัก (Featured Image)"
        name: "featuredImage"
        widget: "image"
        required: true
      - label: "คะแนน (Score)"
        name: "score"
        widget: "number"
        value_type: "float"
        min: 1
        max: 10
        step: 0.1
      - label: "ข้อดี (Pros)"
        name: "pros"
        widget: "list"
        field:
          label: "ข้อดี"
          name: "pro"
          widget: "string"
      - label: "ข้อเสีย (Cons)"
        name: "cons"
        widget: "list"
        field:
          label: "ข้อเสีย"
          name: "con"
          widget: "string"
      - label: "ลิงก์ Affiliate"
        name: "affiliate"
        widget: "object"
        fields:
          - label: "Amazon"
            name: "amazon"
            widget: "string"
            required: false
          - label: "Shopee"
            name: "shopee"
            widget: "string"
            required: false
          - label: "Lazada"
            name: "lazada"
            widget: "string"
            required: false
          - label: "Official Website"
            name: "manufacturer"
            widget: "string"
            required: false
      - label: "เนื้อหาบทความ (Content)"
        name: "body"
        widget: "markdown"
        required: true